[package]
name = "ntumiwa-site"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7"
tower-http = { version = "0.5", features = ["fs"] }
askama = "0.12.1"

[dev-dependencies]
anyhow = "1.0.89"
reqwest = { version = "0.11" }